### ISSUE TITLE
NDEx credentials hard to test

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#10]
As I enter my NDEx credentials, it's important that I get quick feedback on whether I have mistyped. Is there a quick credential test that can happen in the credentials entry box?

**Comment by ericsage** [comment]
There's no API to check if a single field is valid, we can only check all the fields at once. I don't really see this as an issue, but a feature request for the next version. I think we should defer this.

**Comment by bdemchak** [comment]
Error message appears when credential is accepted
