### ISSUE TITLE
Can't see or edit credential

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#11]
I added a credential but cannot edit, view or remove credential. This is critical.

![image](https://user-images.githubusercontent.com/3696094/27091537-40bfcdde-5015-11e7-9c38-cf4185e9539e.png)

**Comment by ericsage** [comment]
I've added a message in the middle of the profile list, if the there are no signed out profiles, it will tell you. This should avoid ambiguity.

**Comment by bdemchak** [comment]
I think the better message would be "No profiles defined". Can you make it more grey, too?? ... still gets your eye.

**Comment by ericsage** [comment]
That wouldn't be right if you had defined a profile and signed in. I can make it more grey though.

**Comment by bdemchak** [comment]
OK
