### ISSUE TITLE
Can't find network by NDEx ID

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#14]
I have an NDEx Id (effd1d7e-4d4e-11e7-8f50-0ac135e8bacf) for a private network (userID: ndex2 cytoapp test, password: ndex2). I'm logged in via CyNDEx2 but if I search on the NDEx ID, I don't find the network. How do I find a network by NDEx ID?

**Comment by ericsage** [comment]
You can't, this has to be built into the NDEx search API.

**Comment by bdemchak** [comment]
Add search example to sample search dropdown

**Comment by dexterpratt** [comment]
Search by uuid

uuid:c8375837-3b42-11e7-8f50-0ac135e8bacf

**Comment by bdemchak** [comment]
On default window in Windows 10, sample query window now scrolls. Can you avoid this??

**Comment by bdemchak** [comment]
Super-useful, by the way ... glad to have this hint available!
