### ISSUE TITLE
Search dropdown persists too long

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#15]
If I enter a search term in the search bar (e.g., effd1d7e-4d4e-11e7-8f50-0ac135e8bacf) and hit Enter, I would expect the search dropdown to disappear and have my search results easily accessible. To get this behavior, I have to find somewhere in the chooser to click, and only then the dropdown disappears. This behavior seems broken.

**Comment by ericsage** [comment]
This is because the menu appears when the searchbar has focus. Hitting enter does not remove focus. Programmatically removing focus isn't possible using React, and it would be unexpected for users using tab to navigate through the UI.
