### ISSUE TITLE
Dates don't include time

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#18]
On both card and table views, the time for create and modify is missing ... can it be added? Is it really helpful to include the Day (e.g., Mon, Tue, etc)?

**Comment by ericsage** [comment]
In my experience, networks do not get changed often. They're usually added and then left to rot, so the date is much more important that the time, and having both is rather crowded.

**Comment by bdemchak** [comment]
Show tool tip that contains time
