### ISSUE TITLE
Chooser filter seems inconsistent

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#21]
I did a search on RBL2, which brought up 64 hits. I then tried the filter "ublic", which brought up two cards. I then tried filter "public", which brought up only one. In both cases, I couldn't figure out why the filter applied to the cards ... and there are plenty of public networks in this set. Is filter working properly?

**Comment by ericsage** [comment]
Yes, the filter filters out keys on the network, so to filter out public networks you must type PUBLIC, not public. The cards you say when you typed in ublic must have had that term somewhere in another field.

**Comment by bdemchak** [comment]
Make search case insensitive

**Comment by bdemchak** [comment]
If I search on rbl2, then enter the filter "ubplic" then type 3, the 3 disappears. If I try to replace the filter with "endo", the "e" is echoed but all other characters I type disappear.

**Comment by bdemchak** [comment]
Seems to work fine ... thanks!
