### ISSUE TITLE
On Save widget, need NDExID discovery

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#22]
To address the likely use case of user trying to tell other users which network to load, the Save widget needs a way of loading NDEx ID into clipboard. When saving New Network, NDEx ID must be available (somehow) after the save.

**Comment by ericsage** [comment]
Seems like we would need add a button to Cytoscape proper.

**Comment by bdemchak** [comment]
When save is complete, display message box indicating status and offering to copy link (UUID) to clipboard. Link must be usable in Chooser widget.

**Comment by bdemchak** [comment]
On Save, expected to be able to copy NDEx ID to clipboard ... is there a button missing??

While it may be convenient to leave this as a message box, in fact I can't select the NDEx ID to manually copy it. Please advise.

**Comment by bdemchak** [comment]
Please improve on the green band by adding a red band and disabling the rest of the dialog box.

**Comment by ericsage** [comment]
Done as described above
