### ISSUE TITLE
Save Crashes if network down

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#27]
If I bring up the Save widget, then pull the network plug, then save the network, I get a crash. It starts out as a hang. If I click on the Save button again, I get the crash.

![image](https://user-images.githubusercontent.com/3696094/27099613-5170f8d6-5030-11e7-898f-7170db90dea4.png)

Recovery after the error is good. Plugging in the network and retrying seems to work.

**Comment by keiono** [comment]
@ericsage Can you catch this error in the client and make it more user-friendly one?

**Comment by bdemchak** [comment]
Same situation, worse error message ... need to fix error message and re-test.


![image](https://user-images.githubusercontent.com/3696094/27204653-2ae4ecd8-51e1-11e7-9796-94a992e638ac.png)
