### ISSUE TITLE
Credential used in Save should persist to Choose

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#30]
If I am in Save and create/use a credential, then I go back to Chooser to load a new network, the credential current for Chooser should be the same as was current for Save. Also, if I return to Save, the previous credential isn't current anymore either. The credential *is* available in the credential list, but I can't make it current, either. Even so, I don't seem to be able to edit the credential, either ... is that intentional?

**Comment by bdemchak** [comment]
This is not fixed. When I have multiple profiles and then choose one, the others disappear and can't be accessed until I sign out of the current profile. Once I do sign out, the multiple profiles are available, though there are also horizontal and vertical scroll bars.

(Can we also make the "Signed out profiles will appear here" much fainter??)

![image](https://user-images.githubusercontent.com/3696094/27299216-7b17f946-54e0-11e7-9278-4f6118a3e4a5.png)

![image](https://user-images.githubusercontent.com/3696094/27299350-f9a493dc-54e0-11e7-9459-df8c0a74c3ac.png)

**Comment by ericsage** [comment]
This is fixed, you can no longer add duplicate profile names, you can only log into one profile at a time.
