### ISSUE TITLE
Installing new CyNDEx JAR leaves old search bar behind

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#33]
In installed .17 over .13 and ended up with two search bars.

Also, I expected a message box telling me to restart Cytoscape, but I didn't get one. Should I have?

![image](https://user-images.githubusercontent.com/3696094/27298283-daa0ac68-54dc-11e7-8a17-f3496af703a8.png)

**Comment by keiono** [comment]
@bdemchak It is a limitation of app updater code in the core.  Do you have the two widgets after restarting Cytoscape?

**Comment by bdemchak** [comment]
Is this limitation because shutdown code isn't called in the app?? Please elaborate. 

I don't have two after restarting ... I have only one.

Should I have seen a "Restart Cytoscape" message?

**Comment by keiono** [comment]
Restart is not necessary for updates because dependencies are already there, but I can ignore them and ask users to restart.

**Comment by bdemchak** [comment]
If you can't clean up after the previous app, perhaps you better ask for a restart. 

Please explain exactly why you can't clean up (???)

**Comment by keiono** [comment]
I've checked the shutdown code and it DOES execute the panel removal method.  I'll double check this is a core issue or a problem in my code.

**Comment by keiono** [comment]
@bdemchak Seems restart is required because the new bundle (new version of CyNDEx-2 and all other apps) starts before the shutdown method is called for the old version, that will end up with unpredictable result.  Also, removing UI before restart is not possible since App Manager never calls stop method in old bundle activator.
