### ISSUE TITLE
Combining new network with NDEx Update causes error

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#35]
If I load galFiltered, then try to save the network but leave the Save as a New Network checkbox unchecked, I get an error (below) during the save. To do this, I had to uncheck the checkbox ... considering that this is a new network, I should not have been able to uncheck the checkbox.

![image](https://user-images.githubusercontent.com/3696094/27305129-431ecbf4-54f5-11e7-969b-e5d506b59b4b.png)

**Comment by ericsage** [comment]
You can no longer uncheck the checkbox
