### ISSUE TITLE
User-Agent can leak sensitive information

### ISSUE THREAD

**Issue by jovimon** [idekerlab/fx-sample#49]
User-Agent can leak sensitive information (company internal username of the user of the app) to the Internet if app installed under user home directory.

Example: 
```User-Agent: C:\Users\<internal_user_ID>\CytoscapeConfiguration\jxbrowser```

Problem is on this line: 
https://github.com/cytoscape/cy-ndex-2/blob/1f001eada37f73f979a851d99b8cad360306bc8d/src/main/java/org/cytoscape/cyndex2/internal/util/BrowserManager.java#L209

It should be commented or some standard value passed so the internal username doesn't get leaked to the network.

Thank you very much.

**Comment by jingjingbic** [comment]
Jxbrowser is no longer used in Cy-NDEx-2.

**Comment by jingjingbic** [comment]
. Jxbrowser is no longer used in Cy-NDEx-2.
