### ISSUE TITLE
JXBrowser version no longer downloadable

### ISSUE THREAD

**Issue by dotasek** [idekerlab/fx-sample#52]
Our version of JXBrowser is 6.20, which is downloaded from https://maven.teamdev.com/repository/products/com/teamdev/jxbrowser/

There is no longer a 6.20 on this site; this breaks JXBrowser on new installs.

**Comment by vladimir-ikryanov** [comment]
I do see the 6.20 version at the given location https://maven.teamdev.com/repository/products/com/teamdev/jxbrowser/jxbrowser-cross-platform/6.20/

**Comment by dotasek** [comment]
Fixed in 2.3.1
