### ISSUE TITLE
NDEx ID not visible?

### ISSUE THREAD

**Issue by bdemchak** [idekerlab/fx-sample#9]
If I want to have a labmate load the same network I loaded, or I want to load a network they tell me about, I think an NDEx ID needs to be available. So far, I don't see a way to get it from the NDEx dialogs or table information. This is critical.

**Comment by bdemchak** [comment]
Will add copy buttons in cards, table and save

**Comment by bdemchak** [comment]
On Save, expected to be able to copy NDEx ID to clipboard ... is there a button missing??

**Comment by ericsage** [comment]
You can copy it manually. We can't put anything in the alert box besides text, and we decided that it's better anyway to be more explicit with what's been generated.

**Comment by bdemchak** [comment]
Moved comment to #22
